CREATE SCHEMA IF NOT EXISTS GymSchema;

DROP TABLE IF EXISTS Gym;
DROP TABLE IF EXISTS Equipment;
DROP TABLE IF EXISTS Customer;

CREATE TABLE Equipment (
	id INT NOT NULL UNIQUE,
	name VARCHAR,
	min_weight FLOAT,
	max_weight FLOAT,
	gym_id INT NOT NULL UNIQUE,
	
	PRIMARY KEY (id),
	FOREIGN KEY (gym_id) REFERENCES Gym (id)
);

CREATE TABLE Gym (
	id INT NOT NULL UNIQUE,
	name VARCHAR NOT NULL UNIQUE,
	address VARCHAR NOT NULL,
	tax_id INT NOT NULL UNIQUE,
	
	PRIMARY KEY (id)
);

CREATE TABLE Customer (
	id INT NOT NULL UNIQUE,
	name VARCHAR NOT NULL,
	address VARCHAR NOT NULL,
	age INT NOT NULL,
	tax_id INT NOT NULL UNIQUE,
	
	PRIMARY KEY (id)
);


